name: Publish

on:
  # publish from the Releases page:
  release:
    types: [published]
  # test publishing just for this PR
  pull_request:

env:
  VERSION_NUMBER: ${{ github.event.release.tag_name || '2.0.5' }}  # TODO: Remove 2.0.5

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Build tools
      run: |
          python -m pip install --upgrade pip
          pip install build
    - name: Replace dummy values in `setup.py` (only for `data-template`)
      if: ${{ github.event.repository.name }} == "data-template"
      run: perl -pi -e 's/\${dataset_name}/template/' setup.py
    - name: Replace version string in `setup.py`
      run: perl -pi -e 's/version="dev"/version="${{ env.VERSION_NUMBER }}"/' setup.py
    - name: Build
      run: |
          python -m build --wheel --sdist
    - name: Publish to Github
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/*'
        fail_on_unmatched_files: true
        tag_name: ${{ env.VERSION_NUMBER }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        # TODO: Replace this personal API token with one that:
        #  - Points at pypi.org, not test.pypi.org
        #  - Is generated by the NeuroPoly PyPI account (https://github.com/neuropoly/onboarding/issues/140)
        password: ${{ secrets.TEST_PYPI_API_TOKEN_JOSHUACWNEWTON }}
        repository_url: https://test.pypi.org/legacy/
